# Thanki Disha Bhagvanjibhai [216270307024]

# practical 5

# 1. Write a numpy program to find the maximum and minimum value of a given flattened array

In [1]:
# importing numpy library
import numpy as np

# creating array
array = np.array([ [1,2,3,4,5,6,7,8,9],[11,22,33,44,55,66,77,88,99] ])
# print array
print("ARRAY : ")
print(array)

# converting array into flattened array
# basically , flattend method convert 2D-array into 1D array !
flattend_array = array.flatten()
print()

#printing flattend_array
print("FLATTEND_ARRAY :")
print(flattend_array)
print()

# maximum value from flattend_array
print("MINIMUM VALUE FROM FLATTEND_ARRAY : ",np.min(flattend_array))
print("MAXIMUM VALUE FROM FLATTEND_ARRAY : ",np.max(flattend_array))

ARRAY : 
[[ 1  2  3  4  5  6  7  8  9]
 [11 22 33 44 55 66 77 88 99]]

FLATTEND_ARRAY :
[ 1  2  3  4  5  6  7  8  9 11 22 33 44 55 66 77 88 99]

MINIMUM VALUE FROM FLATTEND_ARRAY :  1
MAXIMUM VALUE FROM FLATTEND_ARRAY :  99


# 2. Write a numpy program to compute the mean, standard deviation, and variance of a given array along the second axis

In [2]:
# importing numpy library
import numpy as np

# creating array a
a = np.array([ [  [12,12,34] ,[21,23,67] , [21,78,34] ] ])
print("ARRAY A :")
print(a)
print()

# mean of array a along axis=2
print(" MEAN OF AARRAY A ALONG AXIS 2 : ",np.mean(a,axis=2))
print()
# standard deviation of array a along axis=2 
print(" STANDARD DEVIATION OF ARRAY A ALONG AXIS 2 :",np.std(a,axis=2))
print()
#variance pf array a along axis=2
print(" VARIANCE OF ARRAY A ALONG AXIS 2 : ",np.var(a,axis=2))
print()

ARRAY A :
[[[12 12 34]
  [21 23 67]
  [21 78 34]]]

 MEAN OF AARRAY A ALONG AXIS 2 :  [[19.33333333 37.         44.33333333]]

 STANDARD DEVIATION OF ARRAY A ALONG AXIS 2 : [[10.37089946 21.2289111  24.39034417]]

 VARIANCE OF ARRAY A ALONG AXIS 2 :  [[107.55555556 450.66666667 594.88888889]]

