# Thanki Disha Bhagvanjibhai [216270307024]

# Practical 4

# 1. Write a numpy program to add, subtract, multiply, divide arguments element-wise


In [1]:
# importing numpy library 
import numpy as np

# creating array 1 
a1 = np.array([1,2,3,4,5])
# creating array 2
a2 = np.array([1,2,3,4,5])
print()

#addition 
print(" ARRAY 1 + ARRAY 2 : ",np.add(a1,a2))
#subtraction
print(" ARRAY 1 - ARRAY 2 : ",np.subtract(a1,a2))
#multiplication
print(" ARRAY 1 * ARRAY 2 : ",np.multiply(a1,a2))
#divsion
print(" ARRAY 1 / ARRAY 2 : ",np.divide(a1,a2))
print()


 ARRAY 1 + ARRAY 2 :  [ 2  4  6  8 10]
 ARRAY 1 - ARRAY 2 :  [0 0 0 0 0]
 ARRAY 1 * ARRAY 2 :  [ 1  4  9 16 25]
 ARRAY 1 / ARRAY 2 :  [1. 1. 1. 1. 1.]



# 2. Write a numpy program to round elements of the array to the nearest integer

In [2]:
# importing numpy library 
import numpy as np

#creating array 
a = np.array([10.6,20.5,30.3,40.7,50.3])
print(" ARRAY ELEMENTS BEFORE USING ROUND() : ",a)
print()

#rounding elements of array a to their nearest value
print(" ARRAY ELEMENTS AFTER USING ROUND() : ",np.round(a))

 ARRAY ELEMENTS BEFORE USING ROUND() :  [10.6 20.5 30.3 40.7 50.3]

 ARRAY ELEMENTS AFTER USING ROUND() :  [11. 20. 30. 41. 50.]


# 3. Write a numpy program to calculate mean across dimension, in a 2D numpy array


In [3]:
# importing numpy library 
import numpy as np

#creating array 
array = np.array([ [1,2,3,4,5] , [1,2,3,4,5] ])
print()

# printing array
print(array)
# mean along axis 0
print(" MEAN OF ARRAY ALONG AXIS = 0 : ", np.mean(array, axis=0))
# mean along axis 1
print(" MEAN OF ARRAY ALONG AXIS = 1 : ", np.mean(array, axis=1))
print()


[[1 2 3 4 5]
 [1 2 3 4 5]]
 MEAN OF ARRAY ALONG AXIS = 0 :  [1. 2. 3. 4. 5.]
 MEAN OF ARRAY ALONG AXIS = 1 :  [3. 3.]



# 4. Write a program to calculate the difference between neighboring elements, elementwise of a given array

In [4]:
# importing numpy library 
import numpy as np

# creating one dimensonal array 
a1 = np.array([11,22,33,44,55])
# creating two dimensonal array 
a2 = np.array([ [1,22,13] , [48,53,36] ])
# creating three dimensonal array 
a3 = np.array( [  [ [11,22,33] , [43,51,62] , [67,87,34] ] ] )

# finding diffrence for a1 - one dimensonal array
print("DIFFRENCE FOR ARRAY1 l ")
print(np.diff(a1))
print()

# finding diffrence for a2 - Two dimensonal array
print("DIFFRENCE FOR ARRAY1 2 ")
print(np.diff(a2))
print()

# finding diffrence for a3 - Three dimensonal array
print("DIFFRENCE FOR ARRAY1 3 ")
print(np.diff(a3))
print()


DIFFRENCE FOR ARRAY1 l 
[11 11 11 11]

DIFFRENCE FOR ARRAY1 2 
[[ 21  -9]
 [  5 -17]]

DIFFRENCE FOR ARRAY1 3 
[[[ 11  11]
  [  8  11]
  [ 20 -53]]]

